from folio.repositories import BookRepository
from folio.models import Address


class AddressService:
    def __init__(self, repository: AddressRepository): ...
    def add(self, address: Address) -> int: ...
    def list(self) -> list[Address]: ...
