# from folio.repositories import EmploymentRepository
# from folio.models import Employment


# class EmploymentService:
#     def __init__(self, repository: EmploymentRepository): ...
#     def add(self, employment: Employment) -> int: ...
#     def list(self) -> list[Employment]: ...
