from folio.repositories import TravelRepository
from folio.models import Travel


class TravelService:
    def __init__(self, repository: TravelRepository): ...
    def add(self, travel: Travel) -> int: ...
    def list(self) -> list[Travel]: ...
