# from folio.repositories import WorkRepository
# from folio.models import Work


# class WorkService:
#     def __init__(self, repository: WorkRepository): ...
#     def add(self, work: Work) -> int: ...
#     def list(self) -> list[Work]: ...
